### ISSUE TITLE
НИ ОДНОГО JS ФАЙЛА

### ISSUE THREAD

**Issue by ErgerSusha** [AlexYakimovich/poke#1]
УЖАС

**Comment by AlexYakimovich** [comment]
Thank you for your participation in our product development.
You issue means a lot to us and we fixed it in this commit:
https://github.com/AlexYakimovich/poke/commit/04e8fdd6e89985f1ba8f9a7d2b7089b9e22f90e5

Best regards, Alex Yakimovich
